        const FONT_AWESOME_ICONS = [
            { name: 'Shield', unicode: '&#xf132;', className: 'shield-alt' },

            // === BUSINESS & FINANCE ICONS ===
            { name: 'Chart Bar', unicode: '&#xf080;', className: 'chart-bar' },
            { name: 'Chart Line', unicode: '&#xf201;', className: 'chart-line' },
            { name: 'Chart Area', unicode: '&#xf1fe;', className: 'chart-area' },
            { name: 'Chart Pie', unicode: '&#xf200;', className: 'chart-pie' },
            { name: 'Coins', unicode: '&#xf51e;', className: 'coins' },
            { name: 'Credit Card', unicode: '&#xf09d;', className: 'credit-card' },
            { name: 'Briefcase', unicode: '&#xf0b1;', className: 'briefcase' },
            { name: 'Handshake', unicode: '&#xf2b5;', className: 'handshake' },
            { name: 'Calculator', unicode: '&#xf1ec;', className: 'calculator' },
            { name: 'Piggy Bank', unicode: '&#xf4d3;', className: 'piggy-bank' },
            { name: 'Money Bill', unicode: '&#xf0d6;', className: 'money-bill' },
            { name: 'Money Bill Wave', unicode: '&#xf53a;', className: 'money-bill-wave' },
            { name: 'Euro Sign', unicode: '&#xf153;', className: 'euro-sign' },
            { name: 'Dollar Sign', unicode: '&#xf155;', className: 'dollar-sign' },
            { name: 'Pound Sign', unicode: '&#xf154;', className: 'pound-sign' },
            { name: 'Yen Sign', unicode: '&#xf157;', className: 'yen-sign' },
            { name: 'Bitcoin', unicode: '&#xf379;', className: 'bitcoin' },
            { name: 'Ethereum', unicode: '&#xf42e;', className: 'ethereum' },
            { name: 'Donate', unicode: '&#xf4b9;', className: 'donate' },
            { name: 'Funnel Dollar', unicode: '&#xf662;', className: 'funnel-dollar' },
            { name: 'Hand Holding USD', unicode: '&#xf4c0;', className: 'hand-holding-usd' },
            { name: 'Landmark', unicode: '&#xf66f;', className: 'landmark' },
            { name: 'Percentage', unicode: '&#xf295;', className: 'percentage' },
            { name: 'Receipt', unicode: '&#xf543;', className: 'receipt' },
            { name: 'Cash Register', unicode: '&#xf788;', className: 'cash-register' },
            { name: 'File Invoice', unicode: '&#xf570;', className: 'file-invoice' },
            { name: 'File Invoice Dollar', unicode: '&#xf571;', className: 'file-invoice-dollar' },

            // === TECHNOLOGY & COMPUTING ===
            { name: 'Laptop', unicode: '&#xf109;', className: 'laptop' },
            { name: 'Mobile Alt', unicode: '&#xf3cd;', className: 'mobile-alt' },
            { name: 'Desktop', unicode: '&#xf108;', className: 'desktop' },
            { name: 'Server', unicode: '&#xf233;', className: 'server' },
            { name: 'Database', unicode: '&#xf1c0;', className: 'database' },
            { name: 'Wifi', unicode: '&#xf1eb;', className: 'wifi' },
            { name: 'Code', unicode: '&#xf121;', className: 'code' },
            { name: 'Bug', unicode: '&#xf188;', className: 'bug' },
            { name: 'Cloud', unicode: '&#xf0c2;', className: 'cloud' },
            { name: 'Cloud Download', unicode: '&#xf0ed;', className: 'cloud-download-alt' },
            { name: 'Cloud Upload', unicode: '&#xf0ee;', className: 'cloud-upload-alt' },
            { name: 'Hard Drive', unicode: '&#xf0a0;', className: 'hdd' },
            { name: 'Memory', unicode: '&#xf538;', className: 'memory' },
            { name: 'Microchip', unicode: '&#xf2db;', className: 'microchip' },
            { name: 'Network Wired', unicode: '&#xf6ff;', className: 'network-wired' },
            { name: 'Plug', unicode: '&#xf1e6;', className: 'plug' },
            { name: 'Power Off', unicode: '&#xf011;', className: 'power-off' },
            { name: 'Terminal', unicode: '&#xf120;', className: 'terminal' },
            { name: 'Keyboard', unicode: '&#xf11c;', className: 'keyboard' },
            { name: 'Mouse', unicode: '&#xf8cc;', className: 'mouse' },
            { name: 'Tablet', unicode: '&#xf10a;', className: 'tablet-alt' },
            { name: 'Tv', unicode: '&#xf26c;', className: 'tv' },
            { name: 'Digital Tachograph', unicode: '&#xf566;', className: 'digital-tachograph' },
            { name: 'Sim Card', unicode: '&#xf7c4;', className: 'sim-card' },
            { name: 'SD Card', unicode: '&#xf7c2;', className: 'sd-card' },
            { name: 'USB', unicode: '&#xf287;', className: 'usb' },
            { name: 'Ethernet', unicode: '&#xf796;', className: 'ethernet' },
            { name: 'Fingerprint', unicode: '&#xf577;', className: 'fingerprint' },
            { name: 'Robot', unicode: '&#xf544;', className: 'robot' },

            // === COMMUNICATION & SOCIAL ===
            { name: 'Comments', unicode: '&#xf086;', className: 'comments' },
            { name: 'Comment', unicode: '&#xf075;', className: 'comment' },
            { name: 'Comment Dots', unicode: '&#xf4ad;', className: 'comment-dots' },
            { name: 'Video', unicode: '&#xf03d;', className: 'video' },
            { name: 'Microphone', unicode: '&#xf130;', className: 'microphone' },
            { name: 'Bullhorn', unicode: '&#xf0a1;', className: 'bullhorn' },
            { name: 'Rss', unicode: '&#xf09e;', className: 'rss' },
            { name: 'Phone', unicode: '&#xf095;', className: 'phone' },
            { name: 'Phone Alt', unicode: '&#xf879;', className: 'phone-alt' },
            { name: 'Phone Volume', unicode: '&#xf2a0;', className: 'phone-volume' },
            { name: 'Envelope', unicode: '&#xf0e0;', className: 'envelope' },
            { name: 'Envelope Open', unicode: '&#xf2b6;', className: 'envelope-open' },
            { name: 'Mail Bulk', unicode: '&#xf674;', className: 'mail-bulk' },
            { name: 'At', unicode: '&#xf1fa;', className: 'at' },
            { name: 'Broadcast Tower', unicode: '&#xf519;', className: 'broadcast-tower' },
            { name: 'Satellite Dish', unicode: '&#xf7c0;', className: 'satellite-dish' },
            { name: 'Satellite', unicode: '&#xf7bf;', className: 'satellite' },
            { name: 'Podcast', unicode: '&#xf2ce;', className: 'podcast' },
            { name: 'Voicemail', unicode: '&#xf897;', className: 'voicemail' },
            { name: 'Headphones', unicode: '&#xf025;', className: 'headphones' },
            { name: 'Headset', unicode: '&#xf590;', className: 'headset' },
            { name: 'Speakphone', unicode: '&#xf2f2;', className: 'speakerphone' },

            // === SOCIAL MEDIA ===
            { name: 'Facebook', unicode: '&#xf09a;', className: 'facebook' },
            { name: 'Facebook F', unicode: '&#xf39e;', className: 'facebook-f' },
            { name: 'Twitter', unicode: '&#xf099;', className: 'twitter' },
            { name: 'LinkedIn', unicode: '&#xf08c;', className: 'linkedin' },
            { name: 'LinkedIn In', unicode: '&#xf0e1;', className: 'linkedin-in' },
            { name: 'Instagram', unicode: '&#xf16d;', className: 'instagram' },
            { name: 'YouTube', unicode: '&#xf167;', className: 'youtube' },
            { name: 'Share Alt', unicode: '&#xf1e0;', className: 'share-alt' },
            { name: 'Share', unicode: '&#xf064;', className: 'share' },
            { name: 'Share Square', unicode: '&#xf14d;', className: 'share-square' },
            { name: 'Slack', unicode: '&#xf198;', className: 'slack' },
            { name: 'WhatsApp', unicode: '&#xf232;', className: 'whatsapp' },
            { name: 'Telegram', unicode: '&#xf2c6;', className: 'telegram' },
            { name: 'Discord', unicode: '&#xf392;', className: 'discord' },
            { name: 'Skype', unicode: '&#xf17e;', className: 'skype' },
            { name: 'TikTok', unicode: '&#xe07b;', className: 'tiktok' },
            { name: 'Snapchat', unicode: '&#xf2ab;', className: 'snapchat' },
            { name: 'Pinterest', unicode: '&#xf0d2;', className: 'pinterest' },
            { name: 'Tumblr', unicode: '&#xf173;', className: 'tumblr' },
            { name: 'Reddit', unicode: '&#xf1a1;', className: 'reddit' },
            { name: 'Vimeo', unicode: '&#xf40a;', className: 'vimeo' },
            { name: 'Twitch', unicode: '&#xf1e8;', className: 'twitch' },

            // === E-COMMERCE & SHOPPING ===
            { name: 'Shopping Cart', unicode: '&#xf07a;', className: 'shopping-cart' },
            { name: 'Shopping Bag', unicode: '&#xf290;', className: 'shopping-bag' },
            { name: 'Shopping Basket', unicode: '&#xf291;', className: 'shopping-basket' },
            { name: 'Store', unicode: '&#xf54e;', className: 'store' },
            { name: 'Store Alt', unicode: '&#xf54f;', className: 'store-alt' },
            { name: 'Tags', unicode: '&#xf02c;', className: 'tags' },
            { name: 'Tag', unicode: '&#xf02b;', className: 'tag' },
            { name: 'Percent', unicode: '&#xf295;', className: 'percent' },
            { name: 'Barcode', unicode: '&#xf02a;', className: 'barcode' },
            { name: 'QRCode', unicode: '&#xf029;', className: 'qrcode' },
            { name: 'Gift', unicode: '&#xf06b;', className: 'gift' },
            { name: 'Box', unicode: '&#xf466;', className: 'box' },
            { name: 'Boxes', unicode: '&#xf468;', className: 'boxes' },
            { name: 'Package', unicode: '&#xf4c4;', className: 'box-open' },
            { name: 'Warehouse', unicode: '&#xf494;', className: 'warehouse' },
            { name: 'Inventory', unicode: '&#xf480;', className: 'clipboard-list' },
            { name: 'Dolly', unicode: '&#xf472;', className: 'dolly' },
            { name: 'Pallet', unicode: '&#xf482;', className: 'pallet' },
            { name: 'Shipping Fast', unicode: '&#xf48b;', className: 'shipping-fast' },
            { name: 'Truck', unicode: '&#xf0d1;', className: 'truck' },
            { name: 'Truck Loading', unicode: '&#xf4de;', className: 'truck-loading' },

            // === OFFICE & BUSINESS ===
            { name: 'Building', unicode: '&#xf1ad;', className: 'building' },
            { name: 'City', unicode: '&#xf64f;', className: 'city' },
            { name: 'Industry', unicode: '&#xf275;', className: 'industry' },
            { name: 'Factory', unicode: '&#xf275;', className: 'industry' },
            { name: 'Office Building', unicode: '&#xf1ad;', className: 'building' },
            { name: 'Home', unicode: '&#xf015;', className: 'home' },
            { name: 'Address Card', unicode: '&#xf2bb;', className: 'address-card' },
            { name: 'ID Badge', unicode: '&#xf2c1;', className: 'id-badge' },
            { name: 'ID Card', unicode: '&#xf2c2;', className: 'id-card' },
            { name: 'Business Time', unicode: '&#xf64a;', className: 'business-time' },
            { name: 'Tie', unicode: '&#xf553;', className: 'user-tie' },
            { name: 'User Suit', unicode: '&#xf553;', className: 'user-tie' },
            { name: 'Presentation', unicode: '&#xf674;', className: 'chalkboard-teacher' },
            { name: 'Projector', unicode: '&#xf8d2;', className: 'video' },
            { name: 'Meeting', unicode: '&#xf0c0;', className: 'users' },
            { name: 'Conference', unicode: '&#xf086;', className: 'comments' },
            { name: 'Desk', unicode: '&#xf390;', className: 'chair' },
            { name: 'Chair', unicode: '&#xf390;', className: 'chair' },
            { name: 'Coffee', unicode: '&#xf0f4;', className: 'coffee' },
            { name: 'Coffee Cup', unicode: '&#xf0f4;', className: 'coffee' },
            { name: 'Water', unicode: '&#xf773;', className: 'water' },
            { name: 'Restroom', unicode: '&#xf7bd;', className: 'restroom' },

            // === DOCUMENTS & FILES ===
            { name: 'File', unicode: '&#xf15b;', className: 'file' },
            { name: 'File Alt', unicode: '&#xf15c;', className: 'file-alt' },
            { name: 'File PDF', unicode: '&#xf1c1;', className: 'file-pdf' },
            { name: 'File Word', unicode: '&#xf1c2;', className: 'file-word' },
            { name: 'File Excel', unicode: '&#xf1c3;', className: 'file-excel' },
            { name: 'File PowerPoint', unicode: '&#xf1c4;', className: 'file-powerpoint' },
            { name: 'File Image', unicode: '&#xf1c5;', className: 'file-image' },
            { name: 'File Video', unicode: '&#xf1c8;', className: 'file-video' },
            { name: 'File Audio', unicode: '&#xf1c7;', className: 'file-audio' },
            { name: 'File Archive', unicode: '&#xf1c6;', className: 'file-archive' },
            { name: 'File Code', unicode: '&#xf1c9;', className: 'file-code' },
            { name: 'File CSV', unicode: '&#xf6dd;', className: 'file-csv' },
            { name: 'File Download', unicode: '&#xf56d;', className: 'file-download' },
            { name: 'File Upload', unicode: '&#xf574;', className: 'file-upload' },
            { name: 'File Import', unicode: '&#xf56f;', className: 'file-import' },
            { name: 'File Export', unicode: '&#xf56e;', className: 'file-export' },
            { name: 'Folder', unicode: '&#xf07b;', className: 'folder' },
            { name: 'Folder Open', unicode: '&#xf07c;', className: 'folder-open' },
            { name: 'Folder Plus', unicode: '&#xf65e;', className: 'folder-plus' },
            { name: 'Folder Minus', unicode: '&#xf65d;', className: 'folder-minus' },
            { name: 'Archive', unicode: '&#xf187;', className: 'archive' },
            { name: 'Copy', unicode: '&#xf0c5;', className: 'copy' },
            { name: 'Cut', unicode: '&#xf0c4;', className: 'cut' },
            { name: 'Paste', unicode: '&#xf0ea;', className: 'paste' },

            // === SECURITY & COMPLIANCE ===
            { name: 'Key', unicode: '&#xf084;', className: 'key' },
            { name: 'Lock', unicode: '&#xf023;', className: 'lock' },
            { name: 'Lock Open', unicode: '&#xf3c1;', className: 'lock-open' },
            { name: 'Unlock', unicode: '&#xf09c;', className: 'unlock' },
            { name: 'Unlock Alt', unicode: '&#xf13e;', className: 'unlock-alt' },
            { name: 'User Shield', unicode: '&#xf505;', className: 'user-shield' },
            { name: 'Shield Check', unicode: '&#xf2f7;', className: 'shield-check' },
            { name: 'Shield Virus', unicode: '&#xe06c;', className: 'shield-virus' },
            { name: 'User Secret', unicode: '&#xf21b;', className: 'user-secret' },
            { name: 'User Lock', unicode: '&#xf502;', className: 'user-lock' },
            { name: 'Passport', unicode: '&#xf5ab;', className: 'passport' },
            { name: 'Certificate', unicode: '&#xf0a3;', className: 'certificate' },
            { name: 'Award', unicode: '&#xf559;', className: 'award' },
            { name: 'Medal', unicode: '&#xf5a2;', className: 'medal' },
            { name: 'Ribbon', unicode: '&#xf4d6;', className: 'ribbon' },
            { name: 'Badge', unicode: '&#xf335;', className: 'id-badge' },
            { name: 'Signature', unicode: '&#xf5b7;', className: 'signature' },
            { name: 'Stamp', unicode: '&#xf5bf;', className: 'stamp' },
            { name: 'Seal', unicode: '&#xf023;', className: 'lock' },
            { name: 'Gavel', unicode: '&#xf0e3;', className: 'gavel' },
            { name: 'Balance Scale', unicode: '&#xf24e;', className: 'balance-scale' },
            { name: 'Scale Balanced', unicode: '&#xf515;', className: 'balance-scale-right' },
            { name: 'Scales', unicode: '&#xf24e;', className: 'balance-scale' },
            { name: 'Legal', unicode: '&#xf0e3;', className: 'gavel' },
            { name: 'Contract', unicode: '&#xf56c;', className: 'file-contract' },
            { name: 'Document', unicode: '&#xf15b;', className: 'file' },
            { name: 'Clipboard Check', unicode: '&#xf46c;', className: 'clipboard-check' },
            { name: 'Clipboard List', unicode: '&#xf46d;', className: 'clipboard-list' },
            { name: 'Tasks', unicode: '&#xf0ae;', className: 'tasks' },
            { name: 'Checklist', unicode: '&#xf0ae;', className: 'tasks' },

            // === API & INTEGRATION ===
            { name: 'API', unicode: '&#xf7ed;', className: 'project-diagram' },
            { name: 'Code Branch', unicode: '&#xf126;', className: 'code-branch' },
            { name: 'Code Merge', unicode: '&#xf387;', className: 'code-merge' },
            { name: 'Webhook', unicode: '&#xf085;', className: 'cogs' },
            { name: 'Integration', unicode: '&#xf1e6;', className: 'plug' },
            { name: 'Data Exchange', unicode: '&#xf362;', className: 'exchange-alt' },
            { name: 'REST API', unicode: '&#xf0c1;', className: 'link' },
            { name: 'GraphQL', unicode: '&#xf1c0;', className: 'database' },
            { name: 'Microservice', unicode: '&#xf1b2;', className: 'cubes' },
            { name: 'Service', unicode: '&#xf233;', className: 'server' },
            { name: 'Pipeline', unicode: '&#xf101;', className: 'angle-double-right' },
            { name: 'Data Flow', unicode: '&#xf362;', className: 'exchange-alt' },
            { name: 'Endpoint', unicode: '&#xf3c5;', className: 'map-marker-alt' },
            { name: 'Request', unicode: '&#xf0a6;', className: 'hand-point-up' },
            { name: 'Response', unicode: '&#xf0a7;', className: 'hand-point-down' },
            { name: 'JSON', unicode: '&#xf1c9;', className: 'file-code' },
            { name: 'XML', unicode: '&#xf1c9;', className: 'file-code' },
            { name: 'OAuth', unicode: '&#xf084;', className: 'key' },
            { name: 'Token', unicode: '&#xf3ed;', className: 'ticket-alt' },
            { name: 'SDK', unicode: '&#xf1b2;', className: 'cubes' },
            { name: 'Documentation', unicode: '&#xf02d;', className: 'book' },
            { name: 'Postman', unicode: '&#xf0e0;', className: 'envelope' },
            { name: 'Swagger', unicode: '&#xf518;', className: 'book-open' },
            { name: 'Version Control', unicode: '&#xf126;', className: 'code-branch' },
            { name: 'Deployment', unicode: '&#xf135;', className: 'rocket' },
            { name: 'Load Balancer', unicode: '&#xf24e;', className: 'balance-scale' },
            { name: 'Rate Limiting', unicode: '&#xf3fd;', className: 'tachometer-alt' },
            { name: 'Cache', unicode: '&#xf0a0;', className: 'hdd' },
            { name: 'CDN', unicode: '&#xf0ac;', className: 'globe' },
            { name: 'Monitoring', unicode: '&#xf06e;', className: 'eye' },
            { name: 'Analytics', unicode: '&#xf080;', className: 'chart-bar' },
            { name: 'Logs', unicode: '&#xf15c;', className: 'file-alt' },
            { name: 'Debug', unicode: '&#xf188;', className: 'bug' },
            { name: 'Testing', unicode: '&#xf0ae;', className: 'tasks' },
            { name: 'Quality Assurance', unicode: '&#xf2f7;', className: 'shield-check' },

            // === COMPLIANCE & REGULATORY ===
            { name: 'GDPR', unicode: '&#xf2f7;', className: 'shield-check' },
            { name: 'DSGVO', unicode: '&#xf2f7;', className: 'shield-check' },
            { name: 'Privacy Policy', unicode: '&#xf56c;', className: 'file-contract' },
            { name: 'Data Privacy', unicode: '&#xf502;', className: 'user-lock' },
            { name: 'Audit Trail', unicode: '&#xf46d;', className: 'clipboard-list' },
            { name: 'Audit Log', unicode: '&#xf1da;', className: 'history' },
            { name: 'Compliance Check', unicode: '&#xf46c;', className: 'clipboard-check' },
            { name: 'Regulation', unicode: '&#xf0e3;', className: 'gavel' },
            { name: 'Legal Framework', unicode: '&#xf24e;', className: 'balance-scale' },
            { name: 'Policy', unicode: '&#xf15b;', className: 'file' },
            { name: 'Terms of Service', unicode: '&#xf56c;', className: 'file-contract' },
            { name: 'Data Governance', unicode: '&#xf1c0;', className: 'database' },
            { name: 'Risk Assessment', unicode: '&#xf071;', className: 'exclamation-triangle' },
            { name: 'Risk Management', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'Incident Report', unicode: '&#xf06a;', className: 'exclamation-circle' },
            { name: 'Violation Alert', unicode: '&#xf071;', className: 'exclamation-triangle' },
            { name: 'Data Breach', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'Security Audit', unicode: '&#xf023;', className: 'lock' },
            { name: 'Penetration Test', unicode: '&#xf505;', className: 'user-shield' },
            { name: 'Vulnerability', unicode: '&#xf188;', className: 'bug' },
            { name: 'Patch Management', unicode: '&#xf462;', className: 'band-aid' },
            { name: 'Security Update', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'Encryption', unicode: '&#xf023;', className: 'lock' },
            { name: 'Decryption', unicode: '&#xf09c;', className: 'unlock' },
            { name: 'Hash', unicode: '&#xf292;', className: 'hashtag' },
            { name: 'Digital Signature', unicode: '&#xf5b7;', className: 'signature' },
            { name: 'Certificate Authority', unicode: '&#xf0a3;', className: 'certificate' },
            { name: 'Two Factor Auth', unicode: '&#xf3ed;', className: 'ticket-alt' },
            { name: 'Multi Factor Auth', unicode: '&#xf084;', className: 'key' },
            { name: 'Single Sign On', unicode: '&#xf2bd;', className: 'user-circle' },
            { name: 'Access Control', unicode: '&#xf502;', className: 'user-lock' },
            { name: 'Permission', unicode: '&#xf2c1;', className: 'id-badge' },
            { name: 'Authorization', unicode: '&#xf505;', className: 'user-shield' },
            { name: 'Authentication', unicode: '&#xf084;', className: 'key' },
            { name: 'Session Management', unicode: '&#xf017;', className: 'clock' },
            { name: 'Account Lockout', unicode: '&#xf023;', className: 'lock' },
            { name: 'Password Policy', unicode: '&#xf084;', className: 'key' },
            { name: 'Data Retention', unicode: '&#xf187;', className: 'archive' },
            { name: 'Data Deletion', unicode: '&#xf2ed;', className: 'trash-alt' },
            { name: 'Right to be Forgotten', unicode: '&#xf2ed;', className: 'trash-alt' },
            { name: 'Data Portability', unicode: '&#xf56d;', className: 'file-download' },
            { name: 'Data Subject Rights', unicode: '&#xf007;', className: 'user' },
            { name: 'Consent Management', unicode: '&#xf46c;', className: 'clipboard-check' },
            { name: 'Cookie Policy', unicode: '&#xf563;', className: 'cookie' },
            { name: 'Privacy Notice', unicode: '&#xf05a;', className: 'info-circle' },
            { name: 'Data Processing', unicode: '&#xf085;', className: 'cogs' },
            { name: 'Lawful Basis', unicode: '&#xf0e3;', className: 'gavel' },
            { name: 'Legitimate Interest', unicode: '&#xf24e;', className: 'balance-scale' },
            { name: 'Data Controller', unicode: '&#xf4fe;', className: 'user-cog' },
            { name: 'Data Processor', unicode: '&#xf085;', className: 'cogs' },
            { name: 'DPO', unicode: '&#xf505;', className: 'user-shield' },
            { name: 'Data Protection Officer', unicode: '&#xf505;', className: 'user-shield' },
            { name: 'Supervisory Authority', unicode: '&#xf0e3;', className: 'gavel' },
            { name: 'Fine', unicode: '&#xf155;', className: 'dollar-sign' },
            { name: 'Penalty', unicode: '&#xf071;', className: 'exclamation-triangle' },
            { name: 'Sanction', unicode: '&#xf05e;', className: 'ban' },
            { name: 'Non-Compliance', unicode: '&#xf057;', className: 'times-circle' },

            // === ADVANCED SECURITY ===
            { name: 'Firewall', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'Intrusion Detection', unicode: '&#xf06e;', className: 'eye' },
            { name: 'Security Gateway', unicode: '&#xf023;', className: 'lock' },
            { name: 'VPN', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'Proxy', unicode: '&#xf362;', className: 'exchange-alt' },
            { name: 'Load Balancer Security', unicode: '&#xf24e;', className: 'balance-scale' },
            { name: 'DDoS Protection', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'Bot Protection', unicode: '&#xf544;', className: 'robot' },
            { name: 'CAPTCHA', unicode: '&#xf128;', className: 'question' },
            { name: 'Security Headers', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'CSRF Protection', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'XSS Protection', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'SQL Injection Protection', unicode: '&#xf132;', className: 'shield-alt' },
            { name: 'Security Scan', unicode: '&#xf002;', className: 'search' },
            { name: 'Threat Intelligence', unicode: '&#xf0e7;', className: 'bolt' },
            { name: 'Incident Response', unicode: '&#xf0f9;', className: 'ambulance' },
            { name: 'Forensics', unicode: '&#xf002;', className: 'search' },
            { name: 'SIEM', unicode: '&#xf06e;', className: 'eye' },
            { name: 'SOC', unicode: '&#xf233;', className: 'server' },
            { name: 'Security Metrics', unicode: '&#xf080;', className: 'chart-bar' },
            { name: 'Compliance Dashboard', unicode: '&#xf3fd;', className: 'tachometer-alt' },
            { name: 'Security Score', unicode: '&#xf005;', className: 'star' },

            // === WEATHER & NATURE ===
            { name: 'Sun', unicode: '&#xf185;', className: 'sun' },
            { name: 'Moon', unicode: '&#xf186;', className: 'moon' },
            { name: 'Star', unicode: '&#xf005;', className: 'star' },
            { name: 'Cloud', unicode: '&#xf0c2;', className: 'cloud' },
            { name: 'Cloud Rain', unicode: '&#xf73d;', className: 'cloud-rain' },
            { name: 'Cloud Snow', unicode: '&#xf741;', className: 'cloud-snow' },
            { name: 'Snowflake', unicode: '&#xf2dc;', className: 'snowflake' },
            { name: 'Bolt', unicode: '&#xf0e7;', className: 'bolt' },
            { name: 'Temperature High', unicode: '&#xf769;', className: 'temperature-high' },
            { name: 'Temperature Low', unicode: '&#xf76b;', className: 'temperature-low' },
            { name: 'Umbrella', unicode: '&#xf0e9;', className: 'umbrella' },
            { name: 'Wind', unicode: '&#xf72e;', className: 'wind' },
            { name: 'Leaf', unicode: '&#xf06c;', className: 'leaf' },
            { name: 'Tree', unicode: '&#xf1bb;', className: 'tree' },
            { name: 'Seedling', unicode: '&#xf4d8;', className: 'seedling' },
            { name: 'Flower', unicode: '&#xf7ff;', className: 'spa' },
            { name: 'Globe', unicode: '&#xf0ac;', className: 'globe' },
            { name: 'Globe Europe', unicode: '&#xf7a2;', className: 'globe-europe' },
            { name: 'Globe Americas', unicode: '&#xf57d;', className: 'globe-americas' },
            { name: 'Globe Asia', unicode: '&#xf57e;', className: 'globe-asia' },
            { name: 'Globe Africa', unicode: '&#xf57c;', className: 'globe-africa' },
            { name: 'Mountain', unicode: '&#xf6fc;', className: 'mountain' },
            { name: 'Water', unicode: '&#xf773;', className: 'water' },
            { name: 'Fire', unicode: '&#xf06d;', className: 'fire' },
            { name: 'Recycle', unicode: '&#xf1b8;', className: 'recycle' },

            // === MEDICAL & HEALTH ===
            { name: 'Heartbeat', unicode: '&#xf21e;', className: 'heartbeat' },
            { name: 'Heart', unicode: '&#xf004;', className: 'heart' },
            { name: 'Stethoscope', unicode: '&#xf0f1;', className: 'stethoscope' },
            { name: 'Pills', unicode: '&#xf484;', className: 'pills' },
            { name: 'Prescription', unicode: '&#xf5b1;', className: 'prescription' },
            { name: 'Syringe', unicode: '&#xf48e;', className: 'syringe' },
            { name: 'Thermometer', unicode: '&#xf491;', className: 'thermometer' },
            { name: 'Band Aid', unicode: '&#xf462;', className: 'band-aid' },
            { name: 'First Aid', unicode: '&#xf479;', className: 'first-aid' },
            { name: 'Ambulance', unicode: '&#xf0f9;', className: 'ambulance' },
            { name: 'Hospital', unicode: '&#xf0f8;', className: 'hospital' },
            { name: 'Medical Kit', unicode: '&#xf0fa;', className: 'medkit' },
            { name: 'Virus', unicode: '&#xe074;', className: 'virus' },
            { name: 'Shield Virus', unicode: '&#xe06c;', className: 'shield-virus' },
            { name: 'Head Side Mask', unicode: '&#xe063;', className: 'head-side-mask' },
            { name: 'Lungs', unicode: '&#xf604;', className: 'lungs' },
            { name: 'Brain', unicode: '&#xf5dc;', className: 'brain' },
            { name: 'Tooth', unicode: '&#xf5c9;', className: 'tooth' },
            { name: 'Eye', unicode: '&#xf06e;', className: 'eye' },
            { name: 'Eye Slash', unicode: '&#xf070;', className: 'eye-slash' },
            { name: 'Glasses', unicode: '&#xf530;', className: 'glasses' },
            { name: 'Hand Holding Medical', unicode: '&#xe05c;', className: 'hand-holding-medical' },

            // === TRANSPORT & VEHICLES ===
            { name: 'Car', unicode: '&#xf1b9;', className: 'car' },
            { name: 'Car Alt', unicode: '&#xf5de;', className: 'car-alt' },
            { name: 'Car Side', unicode: '&#xf5e4;', className: 'car-side' },
            { name: 'Taxi', unicode: '&#xf1ba;', className: 'taxi' },
            { name: 'Bus', unicode: '&#xf207;', className: 'bus' },
            { name: 'Plane', unicode: '&#xf072;', className: 'plane' },
            { name: 'Plane Departure', unicode: '&#xf5b0;', className: 'plane-departure' },
            { name: 'Plane Arrival', unicode: '&#xf5af;', className: 'plane-arrival' },
            { name: 'Ship', unicode: '&#xf21a;', className: 'ship' },
            { name: 'Anchor', unicode: '&#xf13d;', className: 'anchor' },
            { name: 'Truck', unicode: '&#xf0d1;', className: 'truck' },
            { name: 'Bicycle', unicode: '&#xf206;', className: 'bicycle' },
            { name: 'Motorcycle', unicode: '&#xf21c;', className: 'motorcycle' },
            { name: 'Subway', unicode: '&#xf239;', className: 'subway' },
            { name: 'Train', unicode: '&#xf238;', className: 'train' },
            { name: 'Tram', unicode: '&#xf7da;', className: 'tram' },
            { name: 'Gas Pump', unicode: '&#xf52f;', className: 'gas-pump' },
            { name: 'Parking', unicode: '&#xf540;', className: 'parking' },
            { name: 'Road', unicode: '&#xf018;', className: 'road' },
            { name: 'Traffic Light', unicode: '&#xf637;', className: 'traffic-light' },
            { name: 'Helicopter', unicode: '&#xf533;', className: 'helicopter' },
            { name: 'Rocket', unicode: '&#xf135;', className: 'rocket' },
            { name: 'Satellite', unicode: '&#xf7bf;', className: 'satellite' },
            { name: 'Space Shuttle', unicode: '&#xf197;', className: 'space-shuttle' },

            // === FOOD & DRINK ===
            { name: 'Coffee', unicode: '&#xf0f4;', className: 'coffee' },
            { name: 'Mug Hot', unicode: '&#xf7b6;', className: 'mug-hot' },
            { name: 'Tea', unicode: '&#xf773;', className: 'tea' },
            { name: 'Wine Glass', unicode: '&#xf4e3;', className: 'wine-glass' },
            { name: 'Wine Bottle', unicode: '&#xf72f;', className: 'wine-bottle' },
            { name: 'Beer', unicode: '&#xf0fc;', className: 'beer' },
            { name: 'Cocktail', unicode: '&#xf561;', className: 'cocktail' },
            { name: 'Glass Martini', unicode: '&#xf000;', className: 'glass-martini' },
            { name: 'Utensils', unicode: '&#xf2e7;', className: 'utensils' },
            { name: 'Fork', unicode: '&#xf2e3;', className: 'utensil-fork' },
            { name: 'Knife', unicode: '&#xf2e4;', className: 'utensil-knife' },
            { name: 'Spoon', unicode: '&#xf2e5;', className: 'utensil-spoon' },
            { name: 'Pizza Slice', unicode: '&#xf818;', className: 'pizza-slice' },
            { name: 'Hamburger', unicode: '&#xf805;', className: 'hamburger' },
            { name: 'Hotdog', unicode: '&#xf80f;', className: 'hotdog' },
            { name: 'Bread Slice', unicode: '&#xf7ec;', className: 'bread-slice' },
            { name: 'Cheese', unicode: '&#xf7ef;', className: 'cheese' },
            { name: 'Apple Alt', unicode: '&#xf5d1;', className: 'apple-alt' },
            { name: 'Carrot', unicode: '&#xf787;', className: 'carrot' },
            { name: 'Pepper Hot', unicode: '&#xf816;', className: 'pepper-hot' },
            { name: 'Ice Cream', unicode: '&#xf810;', className: 'ice-cream' },
            { name: 'Cake Candles', unicode: '&#xf1fd;', className: 'birthday-cake' },
            { name: 'Cookie', unicode: '&#xf563;', className: 'cookie' },
            { name: 'Fish', unicode: '&#xf578;', className: 'fish' },
            { name: 'Egg', unicode: '&#xf7fb;', className: 'egg' },
            { name: 'Lemon', unicode: '&#xf094;', className: 'lemon' },
            { name: 'Cookie Bite', unicode: '&#xf564;', className: 'cookie-bite' },

            // === EDUCATION & LEARNING ===
            { name: 'Graduation Cap', unicode: '&#xf19d;', className: 'graduation-cap' },
            { name: 'Book', unicode: '&#xf02d;', className: 'book' },
            { name: 'Book Open', unicode: '&#xf518;', className: 'book-open' },
            { name: 'Book Reader', unicode: '&#xf5da;', className: 'book-reader' },
            { name: 'Books', unicode: '&#xf5db;', className: 'books' },
            { name: 'Bookmark', unicode: '&#xf02e;', className: 'bookmark' },
            { name: 'Journal Whills', unicode: '&#xf66a;', className: 'journal-whills' },
            { name: 'Pencil Alt', unicode: '&#xf303;', className: 'pencil-alt' },
            { name: 'Pen', unicode: '&#xf304;', className: 'pen' },
            { name: 'Pen Fancy', unicode: '&#xf5ac;', className: 'pen-fancy' },
            { name: 'Highlighter', unicode: '&#xf591;', className: 'highlighter' },
            { name: 'Marker', unicode: '&#xf5a1;', className: 'marker' },
            { name: 'Eraser', unicode: '&#xf12d;', className: 'eraser' },
            { name: 'Chalkboard', unicode: '&#xf51b;', className: 'chalkboard' },
            { name: 'Chalkboard Teacher', unicode: '&#xf51c;', className: 'chalkboard-teacher' },
            { name: 'Blackboard', unicode: '&#xf51b;', className: 'chalkboard' },
            { name: 'University', unicode: '&#xf19c;', className: 'university' },
            { name: 'School', unicode: '&#xf549;', className: 'school' },
            { name: 'Student', unicode: '&#xf500;', className: 'user-graduate' },
            { name: 'Teacher', unicode: '&#xf51c;', className: 'chalkboard-teacher' },
            { name: 'Spell Check', unicode: '&#xf891;', className: 'spell-check' },
            { name: 'Language', unicode: '&#xf1ab;', className: 'language' },
            { name: 'Globe', unicode: '&#xf0ac;', className: 'globe' },
            { name: 'Atlas', unicode: '&#xf558;', className: 'atlas' },
            { name: 'Map', unicode: '&#xf279;', className: 'map' },
            { name: 'Compass', unicode: '&#xf14e;', className: 'compass' },
            { name: 'Ruler', unicode: '&#xf545;', className: 'ruler' },
            { name: 'Ruler Combined', unicode: '&#xf546;', className: 'ruler-combined' },
            { name: 'Calculator', unicode: '&#xf1ec;', className: 'calculator' },
            { name: 'Microscope', unicode: '&#xf610;', className: 'microscope' },
            { name: 'Flask', unicode: '&#xf0c3;', className: 'flask' },
            { name: 'Atom', unicode: '&#xf5d2;', className: 'atom' },

            // === SPORTS & RECREATION ===
            { name: 'Futbol', unicode: '&#xf1e3;', className: 'futbol' },
            { name: 'Basketball Ball', unicode: '&#xf434;', className: 'basketball-ball' },
            { name: 'Football Ball', unicode: '&#xf44e;', className: 'football-ball' },
            { name: 'Baseball Ball', unicode: '&#xf433;', className: 'baseball-ball' },
            { name: 'Tennis Ball', unicode: '&#xf43e;', className: 'tennis-ball' },
            { name: 'Volleyball Ball', unicode: '&#xf45f;', className: 'volleyball-ball' },
            { name: 'Table Tennis', unicode: '&#xf45d;', className: 'table-tennis' },
            { name: 'Golf Ball', unicode: '&#xf450;', className: 'golf-ball' },
            { name: 'Hockey Puck', unicode: '&#xf453;', className: 'hockey-puck' },
            { name: 'Bowling Ball', unicode: '&#xf436;', className: 'bowling-ball' },
            { name: 'Dumbbell', unicode: '&#xf44b;', className: 'dumbbell' },
            { name: 'Weight', unicode: '&#xf496;', className: 'weight' },
            { name: 'Swimming Pool', unicode: '&#xf5c5;', className: 'swimming-pool' },
            { name: 'Swimmer', unicode: '&#xf5c4;', className: 'swimmer' },
            { name: 'Running', unicode: '&#xf70c;', className: 'running' },
            { name: 'Walking', unicode: '&#xf554;', className: 'walking' },
            { name: 'Biking', unicode: '&#xf84a;', className: 'biking' },
            { name: 'Skiing', unicode: '&#xf7c9;', className: 'skiing' },
            { name: 'Snowboarding', unicode: '&#xf7ce;', className: 'snowboarding' },
            { name: 'Skating', unicode: '&#xf7c5;', className: 'skating' },
            { name: 'Trophy', unicode: '&#xf091;', className: 'trophy' },
            { name: 'Medal', unicode: '&#xf5a2;', className: 'medal' },
            { name: 'Award', unicode: '&#xf559;', className: 'award' },
            { name: 'Crown', unicode: '&#xf521;', className: 'crown' },
            { name: 'Stopwatch', unicode: '&#xf2f2;', className: 'stopwatch' },
            { name: 'Whistle', unicode: '&#xf460;', className: 'whistle' },
            { name: 'Mountain', unicode: '&#xf6fc;', className: 'mountain' },
            { name: 'Campground', unicode: '&#xf6bb;', className: 'campground' },
            { name: 'Fire', unicode: '&#xf06d;', className: 'fire' },

            // === TOOLS & UTILITIES ===
            { name: 'Wrench', unicode: '&#xf0ad;', className: 'wrench' },
            { name: 'Screwdriver', unicode: '&#xf54a;', className: 'screwdriver' },
            { name: 'Hammer', unicode: '&#xf6e3;', className: 'hammer' },
            { name: 'Saw', unicode: '&#xe68e;', className: 'saw' },
            { name: 'Drill', unicode: '&#xe518;', className: 'drill' },
            { name: 'Toolbox', unicode: '&#xf552;', className: 'toolbox' },
            { name: 'Hard Hat', unicode: '&#xf807;', className: 'hard-hat' },
            { name: 'Cog', unicode: '&#xf013;', className: 'cog' },
            { name: 'Cogs', unicode: '&#xf085;', className: 'cogs' },
            { name: 'Settings', unicode: '&#xf013;', className: 'cog' },
            { name: 'Gear', unicode: '&#xf013;', className: 'cog' },
            { name: 'Tools', unicode: '&#xf7d9;', className: 'tools' },
            { name: 'Nut', unicode: '&#xf111;', className: 'circle' },
            { name: 'Bolt', unicode: '&#xf0e7;', className: 'bolt' },
            { name: 'Screw', unicode: '&#xf54a;', className: 'screwdriver' },
            { name: 'Level', unicode: '&#xe469;', className: 'level' },
            { name: 'Ruler', unicode: '&#xf545;', className: 'ruler' },
            { name: 'Tape', unicode: '&#xf4db;', className: 'tape' },
            { name: 'Flashlight', unicode: '&#xf689;', className: 'flashlight' },
            { name: 'Battery Full', unicode: '&#xf240;', className: 'battery-full' },
            { name: 'Battery Half', unicode: '&#xf242;', className: 'battery-half' },
            { name: 'Battery Empty', unicode: '&#xf244;', className: 'battery-empty' },
            { name: 'Plug', unicode: '&#xf1e6;', className: 'plug' },
            { name: 'Magnet', unicode: '&#xf076;', className: 'magnet' },
            { name: 'Oil Can', unicode: '&#xf613;', className: 'oil-can' },
            { name: 'Spray Can', unicode: '&#xf5bd;', className: 'spray-can' },
            { name: 'Paint Brush', unicode: '&#xf1fc;', className: 'paint-brush' },
            { name: 'Paint Roller', unicode: '&#xf5aa;', className: 'paint-roller' },

            // === TIME & CALENDAR ===
            { name: 'Clock', unicode: '&#xf017;', className: 'clock' },
            { name: 'Stopwatch', unicode: '&#xf2f2;', className: 'stopwatch' },
            { name: 'Hourglass', unicode: '&#xf251;', className: 'hourglass' },
            { name: 'Hourglass Start', unicode: '&#xf251;', className: 'hourglass-start' },
            { name: 'Hourglass Half', unicode: '&#xf252;', className: 'hourglass-half' },
            { name: 'Hourglass End', unicode: '&#xf253;', className: 'hourglass-end' },
            { name: 'Timer', unicode: '&#xf2f2;', className: 'stopwatch' },
            { name: 'Alarm Clock', unicode: '&#xf34e;', className: 'alarm-clock' },
            { name: 'Calendar', unicode: '&#xf073;', className: 'calendar' },
            { name: 'Calendar Alt', unicode: '&#xf073;', className: 'calendar-alt' },
            { name: 'Calendar Check', unicode: '&#xf274;', className: 'calendar-check' },
            { name: 'Calendar Plus', unicode: '&#xf271;', className: 'calendar-plus' },
            { name: 'Calendar Minus', unicode: '&#xf272;', className: 'calendar-minus' },
            { name: 'Calendar Times', unicode: '&#xf273;', className: 'calendar-times' },
            { name: 'Calendar Day', unicode: '&#xf783;', className: 'calendar-day' },
            { name: 'Calendar Week', unicode: '&#xf784;', className: 'calendar-week' },
            { name: 'History', unicode: '&#xf1da;', className: 'history' },
            { name: 'Business Time', unicode: '&#xf64a;', className: 'business-time' },
            { name: 'User Clock', unicode: '&#xf4fd;', className: 'user-clock' },
            { name: 'Clock Rotate Left', unicode: '&#xf1da;', className: 'history' },

            // === NAVIGATION & ARROWS ===
            { name: 'Arrow Right', unicode: '&#xf061;', className: 'arrow-right' },
            { name: 'Arrow Left', unicode: '&#xf060;', className: 'arrow-left' },
            { name: 'Arrow Up', unicode: '&#xf062;', className: 'arrow-up' },
            { name: 'Arrow Down', unicode: '&#xf063;', className: 'arrow-down' },
            { name: 'Arrow Circle Right', unicode: '&#xf0a9;', className: 'arrow-circle-right' },
            { name: 'Arrow Circle Left', unicode: '&#xf0a8;', className: 'arrow-circle-left' },
            { name: 'Arrow Circle Up', unicode: '&#xf0aa;', className: 'arrow-circle-up' },
            { name: 'Arrow Circle Down', unicode: '&#xf0ab;', className: 'arrow-circle-down' },
            { name: 'Chevron Right', unicode: '&#xf054;', className: 'chevron-right' },
            { name: 'Chevron Left', unicode: '&#xf053;', className: 'chevron-left' },
            { name: 'Chevron Up', unicode: '&#xf077;', className: 'chevron-up' },
            { name: 'Chevron Down', unicode: '&#xf078;', className: 'chevron-down' },
            { name: 'Angle Right', unicode: '&#xf105;', className: 'angle-right' },
            { name: 'Angle Left', unicode: '&#xf104;', className: 'angle-left' },
            { name: 'Angle Up', unicode: '&#xf106;', className: 'angle-up' },
            { name: 'Angle Down', unicode: '&#xf107;', className: 'angle-down' },
            { name: 'Angle Double Right', unicode: '&#xf101;', className: 'angle-double-right' },
            { name: 'Angle Double Left', unicode: '&#xf100;', className: 'angle-double-left' },
            { name: 'Angle Double Up', unicode: '&#xf102;', className: 'angle-double-up' },
            { name: 'Angle Double Down', unicode: '&#xf103;', className: 'angle-double-down' },
            { name: 'Caret Right', unicode: '&#xf0da;', className: 'caret-right' },
            { name: 'Caret Left', unicode: '&#xf0d9;', className: 'caret-left' },
            { name: 'Caret Up', unicode: '&#xf0d8;', className: 'caret-up' },
            { name: 'Caret Down', unicode: '&#xf0d7;', className: 'caret-down' },
            { name: 'Long Arrow Alt Right', unicode: '&#xf30b;', className: 'long-arrow-alt-right' },
            { name: 'Long Arrow Alt Left', unicode: '&#xf30a;', className: 'long-arrow-alt-left' },
            { name: 'Long Arrow Alt Up', unicode: '&#xf30c;', className: 'long-arrow-alt-up' },
            { name: 'Long Arrow Alt Down', unicode: '&#xf309;', className: 'long-arrow-alt-down' },
            { name: 'Location Arrow', unicode: '&#xf124;', className: 'location-arrow' },
            { name: 'Compass', unicode: '&#xf14e;', className: 'compass' },
            { name: 'Directions', unicode: '&#xf5eb;', className: 'directions' },
            { name: 'Map Marker', unicode: '&#xf3c5;', className: 'map-marker-alt' },
            { name: 'Map Pin', unicode: '&#xf276;', className: 'map-pin' },
            { name: 'Route', unicode: '&#xf4d7;', className: 'route' },
            { name: 'Share', unicode: '&#xf064;', className: 'share' },
            { name: 'Reply', unicode: '&#xf3e5;', className: 'reply' },
            { name: 'Forward', unicode: '&#xf04e;', className: 'forward' },
            { name: 'Undo', unicode: '&#xf0e2;', className: 'undo' },
            { name: 'Redo', unicode: '&#xf01e;', className: 'redo' },
            { name: 'Sync', unicode: '&#xf021;', className: 'sync' },
            { name: 'Refresh', unicode: '&#xf021;', className: 'sync' },
            { name: 'Reload', unicode: '&#xf021;', className: 'sync' },
            { name: 'Repeat', unicode: '&#xf01e;', className: 'redo' },
            { name: 'Random', unicode: '&#xf074;', className: 'random' },
            { name: 'Shuffle', unicode: '&#xf074;', className: 'random' },

            // === ACTIONS & CONTROLS ===
            { name: 'Play', unicode: '&#xf04b;', className: 'play' },
            { name: 'Pause', unicode: '&#xf04c;', className: 'pause' },
            { name: 'Stop', unicode: '&#xf04d;', className: 'stop' },
            { name: 'Fast Forward', unicode: '&#xf04e;', className: 'fast-forward' },
            { name: 'Fast Backward', unicode: '&#xf049;', className: 'fast-backward' },
            { name: 'Step Forward', unicode: '&#xf051;', className: 'step-forward' },
            { name: 'Step Backward', unicode: '&#xf048;', className: 'step-backward' },
            { name: 'Eject', unicode: '&#xf052;', className: 'eject' },
            { name: 'Volume Up', unicode: '&#xf028;', className: 'volume-up' },
            { name: 'Volume Down', unicode: '&#xf027;', className: 'volume-down' },
            { name: 'Volume Off', unicode: '&#xf026;', className: 'volume-off' },
            { name: 'Volume Mute', unicode: '&#xf6a9;', className: 'volume-mute' },
            { name: 'Microphone', unicode: '&#xf130;', className: 'microphone' },
            { name: 'Microphone Slash', unicode: '&#xf131;', className: 'microphone-slash' },
            { name: 'Download', unicode: '&#xf019;', className: 'download' },
            { name: 'Upload', unicode: '&#xf093;', className: 'upload' },
            { name: 'Save', unicode: '&#xf0c7;', className: 'save' },
            { name: 'Floppy Disk', unicode: '&#xf0c7;', className: 'save' },
            { name: 'Print', unicode: '&#xf02f;', className: 'print' },
            { name: 'Printer', unicode: '&#xf02f;', className: 'print' },
            { name: 'Fax', unicode: '&#xf1ac;', className: 'fax' },
            { name: 'Scanner', unicode: '&#xf488;', className: 'scanner' },
            { name: 'Copy', unicode: '&#xf0c5;', className: 'copy' },
            { name: 'Cut', unicode: '&#xf0c4;', className: 'cut' },
            { name: 'Paste', unicode: '&#xf0ea;', className: 'paste' },
            { name: 'Edit', unicode: '&#xf044;', className: 'edit' },
            { name: 'Pen', unicode: '&#xf304;', className: 'pen' },
            { name: 'Pencil', unicode: '&#xf303;', className: 'pencil-alt' },
            { name: 'Eraser', unicode: '&#xf12d;', className: 'eraser' },
            { name: 'Trash', unicode: '&#xf1f8;', className: 'trash' },
            { name: 'Trash Alt', unicode: '&#xf2ed;', className: 'trash-alt' },
            { name: 'Delete', unicode: '&#xf1f8;', className: 'trash' },
            { name: 'Remove', unicode: '&#xf1f8;', className: 'trash' },
            { name: 'Close', unicode: '&#xf00d;', className: 'times' },
            { name: 'Times', unicode: '&#xf00d;', className: 'times' },
            { name: 'X', unicode: '&#xf00d;', className: 'times' },
            { name: 'Plus', unicode: '&#xf067;', className: 'plus' },
            { name: 'Add', unicode: '&#xf067;', className: 'plus' },
            { name: 'Minus', unicode: '&#xf068;', className: 'minus' },
            { name: 'Subtract', unicode: '&#xf068;', className: 'minus' },
            { name: 'Check', unicode: '&#xf00c;', className: 'check' },
            { name: 'Checkmark', unicode: '&#xf00c;', className: 'check' },
            { name: 'Check Circle', unicode: '&#xf058;', className: 'check-circle' },
            { name: 'Check Square', unicode: '&#xf14a;', className: 'check-square' },
            { name: 'Times Circle', unicode: '&#xf057;', className: 'times-circle' },
            { name: 'Exclamation', unicode: '&#xf12a;', className: 'exclamation' },
            { name: 'Exclamation Circle', unicode: '&#xf06a;', className: 'exclamation-circle' },
            { name: 'Exclamation Triangle', unicode: '&#xf071;', className: 'exclamation-triangle' },
            { name: 'Warning', unicode: '&#xf071;', className: 'exclamation-triangle' },
            { name: 'Alert', unicode: '&#xf071;', className: 'exclamation-triangle' },
            { name: 'Question', unicode: '&#xf128;', className: 'question' },
            { name: 'Question Circle', unicode: '&#xf059;', className: 'question-circle' },
            { name: 'Info', unicode: '&#xf129;', className: 'info' },
            { name: 'Info Circle', unicode: '&#xf05a;', className: 'info-circle' },
            { name: 'Ban', unicode: '&#xf05e;', className: 'ban' },
            { name: 'Prohibited', unicode: '&#xf05e;', className: 'ban' },
            { name: 'Not Allowed', unicode: '&#xf05e;', className: 'ban' },

            // === USER & PEOPLE ===
            { name: 'User', unicode: '&#xf007;', className: 'user' },
            { name: 'User Circle', unicode: '&#xf2bd;', className: 'user-circle' },
            { name: 'User Alt', unicode: '&#xf406;', className: 'user-alt' },
            { name: 'Users', unicode: '&#xf0c0;', className: 'users' },
            { name: 'User Friends', unicode: '&#xf500;', className: 'user-friends' },
            { name: 'User Plus', unicode: '&#xf234;', className: 'user-plus' },
            { name: 'User Minus', unicode: '&#xf503;', className: 'user-minus' },
            { name: 'User Times', unicode: '&#xf235;', className: 'user-times' },
            { name: 'User Check', unicode: '&#xf4fc;', className: 'user-check' },
            { name: 'User Cog', unicode: '&#xf4fe;', className: 'user-cog' },
            { name: 'User Edit', unicode: '&#xf4ff;', className: 'user-edit' },
            { name: 'User Shield', unicode: '&#xf505;', className: 'user-shield' },
            { name: 'User Lock', unicode: '&#xf502;', className: 'user-lock' },
            { name: 'User Secret', unicode: '&#xf21b;', className: 'user-secret' },
            { name: 'User Tie', unicode: '&#xf553;', className: 'user-tie' },
            { name: 'User Graduate', unicode: '&#xf501;', className: 'user-graduate' },
            { name: 'User Nurse', unicode: '&#xf82f;', className: 'user-nurse' },
            { name: 'User MD', unicode: '&#xf0f0;', className: 'user-md' },
            { name: 'User Tag', unicode: '&#xf507;', className: 'user-tag' },
            { name: 'User Clock', unicode: '&#xf4fd;', className: 'user-clock' },
            { name: 'Address Card', unicode: '&#xf2bb;', className: 'address-card' },
            { name: 'Address Book', unicode: '&#xf2b9;', className: 'address-book' },
            { name: 'ID Badge', unicode: '&#xf2c1;', className: 'id-badge' },
            { name: 'ID Card', unicode: '&#xf2c2;', className: 'id-card' },
            { name: 'Portrait', unicode: '&#xf3e0;', className: 'portrait' },
            { name: 'Male', unicode: '&#xf183;', className: 'male' },
            { name: 'Female', unicode: '&#xf182;', className: 'female' },
            { name: 'Child', unicode: '&#xf1ae;', className: 'child' },
            { name: 'Baby', unicode: '&#xf77c;', className: 'baby' },
            { name: 'Smile', unicode: '&#xf118;', className: 'smile' },
            { name: 'Laugh', unicode: '&#xf599;', className: 'laugh' },
            { name: 'Grin', unicode: '&#xf580;', className: 'grin' },
            { name: 'Frown', unicode: '&#xf119;', className: 'frown' },
            { name: 'Sad Tear', unicode: '&#xf5b4;', className: 'sad-tear' },
            { name: 'Angry', unicode: '&#xf556;', className: 'angry' },
            { name: 'Surprise', unicode: '&#xf5c2;', className: 'surprise' },
            { name: 'Meh', unicode: '&#xf11a;', className: 'meh' },
            { name: 'Kiss', unicode: '&#xf596;', className: 'kiss' },
            { name: 'Wink', unicode: '&#xf4da;', className: 'grin-wink' },
            { name: 'Thumbs Up', unicode: '&#xf164;', className: 'thumbs-up' },
            { name: 'Thumbs Down', unicode: '&#xf165;', className: 'thumbs-down' },
            { name: 'Hand Paper', unicode: '&#xf256;', className: 'hand-paper' },
            { name: 'Hand Rock', unicode: '&#xf255;', className: 'hand-rock' },
            { name: 'Hand Scissors', unicode: '&#xf257;', className: 'hand-scissors' },
            { name: 'Hand Spock', unicode: '&#xf259;', className: 'hand-spock' },
            { name: 'Hand Lizard', unicode: '&#xf258;', className: 'hand-lizard' },
            { name: 'Hand Peace', unicode: '&#xf25b;', className: 'hand-peace' },
            { name: 'Hand Point Right', unicode: '&#xf0a4;', className: 'hand-point-right' },
            { name: 'Hand Point Left', unicode: '&#xf0a5;', className: 'hand-point-left' },
            { name: 'Hand Point Up', unicode: '&#xf0a6;', className: 'hand-point-up' },
            { name: 'Hand Point Down', unicode: '&#xf0a7;', className: 'hand-point-down' },
            { name: 'Handshake', unicode: '&#xf2b5;', className: 'handshake' },
            { name: 'Fist Raised', unicode: '&#xf6de;', className: 'fist-raised' },
            { name: 'Praying Hands', unicode: '&#xf684;', className: 'praying-hands' },

            // === NUMBERS & SYMBOLS ===
            { name: '0', unicode: '&#xf10f;', className: 'circle' },
            { name: '1', unicode: '&#xf1c0;', className: 'database' },
            { name: '2', unicode: '&#xf1c1;', className: 'file-pdf' },
            { name: '3', unicode: '&#xf1c2;', className: 'file-word' },
            { name: '4', unicode: '&#xf1c3;', className: 'file-excel' },
            { name: '5', unicode: '&#xf1c4;', className: 'file-powerpoint' },
            { name: '6', unicode: '&#xf1c5;', className: 'file-image' },
            { name: '7', unicode: '&#xf1c6;', className: 'file-archive' },
            { name: '8', unicode: '&#xf1c7;', className: 'file-audio' },
            { name: '9', unicode: '&#xf1c8;', className: 'file-video' },
            { name: 'Hashtag', unicode: '&#xf292;', className: 'hashtag' },
            { name: 'Number', unicode: '&#xf292;', className: 'hashtag' },
            { name: 'Asterisk', unicode: '&#xf069;', className: 'asterisk' },
            { name: 'Slash', unicode: '&#xf715;', className: 'slash' },
            { name: 'Backslash', unicode: '&#xf715;', className: 'slash' },
            { name: 'At Symbol', unicode: '&#xf1fa;', className: 'at' },
            { name: 'Ampersand', unicode: '&#xf8ff;', className: 'ampersand' },
            { name: 'Copyright', unicode: '&#xf1f9;', className: 'copyright' },
            { name: 'Registered', unicode: '&#xf25d;', className: 'registered' },
            { name: 'Trademark', unicode: '&#xf25c;', className: 'trademark' },
            { name: 'Paragraph', unicode: '&#xf1dd;', className: 'paragraph' },
            { name: 'Section', unicode: '&#xf6d1;', className: 'section' },
            { name: 'Ellipsis H', unicode: '&#xf141;', className: 'ellipsis-h' },
            { name: 'Ellipsis V', unicode: '&#xf142;', className: 'ellipsis-v' },
            { name: 'Equals', unicode: '&#xf52c;', className: 'equals' },
            { name: 'Not Equal', unicode: '&#xf53e;', className: 'not-equal' },
            { name: 'Greater Than', unicode: '&#xf531;', className: 'greater-than' },
            { name: 'Less Than', unicode: '&#xf536;', className: 'less-than' },
            { name: 'Greater Than Equal', unicode: '&#xf532;', className: 'greater-than-equal' },
            { name: 'Less Than Equal', unicode: '&#xf537;', className: 'less-than-equal' },
            { name: 'Infinity', unicode: '&#xf534;', className: 'infinity' },
            { name: 'Percent', unicode: '&#xf295;', className: 'percent' },
            { name: 'Plus Minus', unicode: '&#xf067;', className: 'plus-minus' },
            { name: 'Divide', unicode: '&#xf529;', className: 'divide' },
            { name: 'Multiply', unicode: '&#xf00d;', className: 'times' },
            { name: 'Superscript', unicode: '&#xf12b;', className: 'superscript' },
            { name: 'Subscript', unicode: '&#xf12c;', className: 'subscript' },
            { name: 'Function', unicode: '&#xf661;', className: 'function' },
            { name: 'Square Root', unicode: '&#xf697;', className: 'square-root-alt' },

            // === MISCELLANEOUS ===
            { name: 'Magic', unicode: '&#xf0d0;', className: 'magic' },
            { name: 'Wand', unicode: '&#xf0d0;', className: 'magic' },
            { name: 'Sparkles', unicode: '&#xf890;', className: 'sparkles' },
            { name: 'Dice', unicode: '&#xf522;', className: 'dice' },
            { name: 'Puzzle Piece', unicode: '&#xf12e;', className: 'puzzle-piece' },
            { name: 'Lightbulb', unicode: '&#xf0eb;', className: 'lightbulb' },
            { name: 'Idea', unicode: '&#xf0eb;', className: 'lightbulb' },
            { name: 'Battery Full', unicode: '&#xf240;', className: 'battery-full' },
            { name: 'Bell', unicode: '&#xf0f3;', className: 'bell' },
            { name: 'Bell Slash', unicode: '&#xf1f6;', className: 'bell-slash' },
            { name: 'Bookmark', unicode: '&#xf02e;', className: 'bookmark' },
            { name: 'Flag', unicode: '&#xf024;', className: 'flag' },
            { name: 'Flag Checkered', unicode: '&#xf11e;', className: 'flag-checkered' },
            { name: 'Gift', unicode: '&#xf06b;', className: 'gift' },
            { name: 'Link', unicode: '&#xf0c1;', className: 'link' },
            { name: 'Unlink', unicode: '&#xf127;', className: 'unlink' },
            { name: 'External Link', unicode: '&#xf35d;', className: 'external-link-alt' },
            { name: 'Anchor', unicode: '&#xf13d;', className: 'anchor' },
            { name: 'Paperclip', unicode: '&#xf0c6;', className: 'paperclip' },
            { name: 'Thumbtack', unicode: '&#xf08d;', className: 'thumbtack' },
            { name: 'Pin', unicode: '&#xf08d;', className: 'thumbtack' },
            { name: 'Map Marker', unicode: '&#xf3c5;', className: 'map-marker-alt' },
            { name: 'Location', unicode: '&#xf3c5;', className: 'map-marker-alt' },
            { name: 'Search', unicode: '&#xf002;', className: 'search' },
            { name: 'Search Plus', unicode: '&#xf00e;', className: 'search-plus' },
            { name: 'Search Minus', unicode: '&#xf010;', className: 'search-minus' },
            { name: 'Filter', unicode: '&#xf0b0;', className: 'filter' },
            { name: 'Sort', unicode: '&#xf0dc;', className: 'sort' },
            { name: 'Sort Up', unicode: '&#xf0de;', className: 'sort-up' },
            { name: 'Sort Down', unicode: '&#xf0dd;', className: 'sort-down' },
            { name: 'Sort Alpha Down', unicode: '&#xf15d;', className: 'sort-alpha-down' },
            { name: 'Sort Alpha Up', unicode: '&#xf15e;', className: 'sort-alpha-up' },
            { name: 'Sort Numeric Down', unicode: '&#xf162;', className: 'sort-numeric-down' },
            { name: 'Sort Numeric Up', unicode: '&#xf163;', className: 'sort-numeric-up' },
            { name: 'Random', unicode: '&#xf074;', className: 'random' },
            { name: 'Retweet', unicode: '&#xf079;', className: 'retweet' },
            { name: 'Sitemap', unicode: '&#xf0e8;', className: 'sitemap' },
            { name: 'List', unicode: '&#xf03a;', className: 'list' },
            { name: 'List Ul', unicode: '&#xf0ca;', className: 'list-ul' },
            { name: 'List Ol', unicode: '&#xf0cb;', className: 'list-ol' },
            { name: 'Th', unicode: '&#xf00a;', className: 'th' },
            { name: 'Th Large', unicode: '&#xf009;', className: 'th-large' },
            { name: 'Th List', unicode: '&#xf00b;', className: 'th-list' },
            { name: 'Bars', unicode: '&#xf0c9;', className: 'bars' },
            { name: 'Menu', unicode: '&#xf0c9;', className: 'bars' },
            { name: 'Hamburger', unicode: '&#xf0c9;', className: 'bars' },
            { name: 'Ellipsis H', unicode: '&#xf141;', className: 'ellipsis-h' },
            { name: 'Ellipsis V', unicode: '&#xf142;', className: 'ellipsis-v' },
            { name: 'Grip Horizontal', unicode: '&#xf58d;', className: 'grip-horizontal' },
            { name: 'Grip Vertical', unicode: '&#xf58e;', className: 'grip-vertical' },
            { name: 'Sliders H', unicode: '&#xf1de;', className: 'sliders-h' },
            { name: 'Toggle Off', unicode: '&#xf204;', className: 'toggle-off' },
            { name: 'Toggle On', unicode: '&#xf205;', className: 'toggle-on' },
            { name: 'Power Off', unicode: '&#xf011;', className: 'power-off' },
            { name: 'Crosshairs', unicode: '&#xf05b;', className: 'crosshairs' },
            { name: 'Expand', unicode: '&#xf065;', className: 'expand' },
            { name: 'Compress', unicode: '&#xf066;', className: 'compress' },
            { name: 'Expand Arrows Alt', unicode: '&#xf31e;', className: 'expand-arrows-alt' },
            { name: 'Compress Arrows Alt', unicode: '&#xf422;', className: 'compress-arrows-alt' },
            { name: 'External Link Square', unicode: '&#xf360;', className: 'external-link-square-alt' },
            { name: 'Spinner', unicode: '&#xf110;', className: 'spinner' },
            { name: 'Circle Notch', unicode: '&#xf1ce;', className: 'circle-notch' },
            { name: 'Cog', unicode: '&#xf013;', className: 'cog' },
            { name: 'Sync Alt', unicode: '&#xf2f1;', className: 'sync-alt' },
            { name: 'Redo Alt', unicode: '&#xf2f9;', className: 'redo-alt' },
            { name: 'Undo Alt', unicode: '&#xf2ea;', className: 'undo-alt' },
            { name: 'Exchange Alt', unicode: '&#xf362;', className: 'exchange-alt' },
            { name: 'Recycle', unicode: '&#xf1b8;', className: 'recycle' },
            { name: 'Tint', unicode: '&#xf043;', className: 'tint' },
            { name: 'Tint Slash', unicode: '&#xf5c7;', className: 'tint-slash' },
            { name: 'Paint Brush', unicode: '&#xf1fc;', className: 'paint-brush' },
            { name: 'Palette', unicode: '&#xf53f;', className: 'palette' },
            { name: 'Swatchbook', unicode: '&#xf5c3;', className: 'swatchbook' },
            { name: 'Fill', unicode: '&#xf575;', className: 'fill' },
            { name: 'Fill Drip', unicode: '&#xf576;', className: 'fill-drip' },
            { name: 'Eraser', unicode: '&#xf12d;', className: 'eraser' },
            { name: 'Clone', unicode: '&#xf24d;', className: 'clone' },
            { name: 'Object Group', unicode: '&#xf247;', className: 'object-group' },
            { name: 'Object Ungroup', unicode: '&#xf248;', className: 'object-ungroup' },
            { name: 'Vector Square', unicode: '&#xf5cb;', className: 'vector-square' },
            { name: 'Draw Polygon', unicode: '&#xf5ee;', className: 'draw-polygon' },
            { name: 'Highlighter', unicode: '&#xf591;', className: 'highlighter' },
            { name: 'Crop', unicode: '&#xf125;', className: 'crop' },
            { name: 'Crop Alt', unicode: '&#xf565;', className: 'crop-alt' },
            { name: 'Bezier Curve', unicode: '&#xf55b;', className: 'bezier-curve' },
            { name: 'Pen Tool', unicode: '&#xf304;', className: 'pen' },
            { name: 'Pen Nib', unicode: '&#xf5ad;', className: 'pen-nib' },
            { name: 'Pen Fancy', unicode: '&#xf5ac;', className: 'pen-fancy' },
            { name: 'Pen Square', unicode: '&#xf14b;', className: 'pen-square' },
            { name: 'Feather', unicode: '&#xf52d;', className: 'feather' },
            { name: 'Feather Alt', unicode: '&#xf56b;', className: 'feather-alt' },
            { name: 'Quill Pen', unicode: '&#xf5ad;', className: 'pen-nib' }
        ];

// Global verfügbar machen
window.FONT_AWESOME_ICONS = FONT_AWESOME_ICONS;

// Icon-Picker Error-Handling hinzufügen
function validateIconPicker() {
    if (!window.FONT_AWESOME_ICONS || FONT_AWESOME_ICONS.length === 0) {
        console.warn('FONT_AWESOME_ICONS nicht gefunden - lade Fallback Icons');
        window.FONT_AWESOME_ICONS = [
            { name: 'check', unicode: '&#xf00c;' },
            { name: 'star', unicode: '&#xf005;' },
            { name: 'heart', unicode: '&#xf004;' },
            { name: 'user', unicode: '&#xf007;' },
            { name: 'envelope', unicode: '&#xf0e0;' },
            { name: 'phone', unicode: '&#xf095;' },
            { name: 'home', unicode: '&#xf015;' },
            { name: 'cog', unicode: '&#xf013;' },
            { name: 'arrow-right', unicode: '&#xf061;' },
            { name: 'shield', unicode: '&#xf132;' }
        ];
    }
}

// Initialisierung
document.addEventListener('DOMContentLoaded', function() {
    validateIconPicker();
    console.log('Icon-Picker initialisiert mit', FONT_AWESOME_ICONS.length, 'Icons');
});        